### PR TITLE
support beta release

### LINKED ISSUE #2503: Updates to ASA template - ReadMe, Pipeline Configs etc

### PR DESCRIPTION
**Pull request by yiliuTo**
## Purpose
The ASA-AZD integration will go to beta feature soon. This pr is to resolve https://github.com/Azure/azure-dev/issues/2503 to update the template compatible with the beta feature.

## Does this introduce a breaking change?

```
[x] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## Others to check
This pr should not be merged until AZD releases ASA as the beta feature, ref https://github.com/Azure/azure-dev/milestone/18

## How to test
When AZD 1.2.0 gets released, run the following commands:
```
mkdir ASA-Samples-Event-Driven-Application
cd ASA-Samples-Event-Driven-Application
azd auth login
azd init --template https://github.com/yiliuTo/ASA-Samples-Event-Driven-Application -b support-beta
azd up
```

### CODE REVIEW

**Comment by yiliuTo** [comment]
Hi @fangjian0423 and @rajeshkamal5050, please help to review this pr, thanks

**Comment by rajeshkamal5050** [comment]
LGTM @yiliuTo

Can we also update the template to consume GHA action and Azd as DevContainer features?

**Comment by fangjian0423** [comment]
hey @rajeshkamal5050

- For GHA action: we have updated `.github/workflows/azure-dev.yml`, it means GHA action already support. It that correct?
- For Devcontainer feature: we have updated `.devcontainer/Dockerfile`, do you mean we should also support devcontainer.json, or we should support both?

**Comment by rajeshkamal5050** [comment]
@fangjian0423 @yiliuTo was referring to use as such for
- GHA Action ` Azure/setup-azd@v0.1.0` ex: https://github.com/Azure-Samples/todo-python-mongo/blob/main/.github/workflows/azure-dev.yml#L32
- Azd as DevContainer feature `ghcr.io/azure/azure-dev/azd:latest` ex: https://github.com/Azure-Samples/todo-python-mongo/blob/main/.devcontainer/devcontainer.json#L11 `Dockerfile` will not be needed too.

**Comment by vhvb1989** [comment]
@fangjian0423 @yiliuTo , I have created this PR: https://github.com/yiliuTo/ASA-Samples-Event-Driven-Application/pull/1/files

It shows the required/missing changes on this PR. 
I tried to push the changes directly here, but I had no access :(

There are 3 main changes:
- Remove the dockerfile
- Update the devcontainer definition to use the Javascript base image plus the azd-devcontainer-feature (plus the Java-feature)
- Update the github workflow to use the azd-action and to install java as part of the flow.

**Review by vhvb1989 — APPROVED** [review]

**Review by stliu — APPROVED** [review]

**Pull request merged**
